### ISSUE TITLE
Doesn't work at CentOS6 due to unsupported systemctl

### ISSUE THREAD

**Issue by toru-takahashi** [fluent/diagtool#8]
CentOS6 uses service command instead of systemctl. Diagtool shows the following error.
It would be helpful if we can skip unsupported commands and then show a result of only supported command in the log

```
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/bin/fluent-diagtool --precheck -t fluentd
/opt/td-agent/embedded/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - systemctl (Errno::ENOENT)
from /opt/td-agent/embedded/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
from /opt/td-agent/embedded/lib/ruby/2.4.0/open3.rb:95:in `popen3'
from /opt/td-agent/embedded/lib/ruby/2.4.0/open3.rb:258:in `capture3'
from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-diagtool-1.0.1/lib/fluent/diagtool/collectutils.rb:107:in `_find_fluentd_info'
from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-diagtool-1.0.1/lib/fluent/diagtool/collectutils.rb:42:in `initialize'
from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-diagtool-1.0.1/lib/fluent/diagtool/diagutils.rb:43:in `new'
from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-diagtool-1.0.1/lib/fluent/diagtool/diagutils.rb:43:in `run_precheck'
from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-diagtool-1.0.1/exe/fluent-diagtool:42:in `<top (required)>'
from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/bin/fluent-diagtool:23:in `load'
from /opt/td-agent/embedded/lib/ruby/gems/2.4.0/bin/fluent-diagtool:23:in `<main>'
```

**Comment by kenhys** [comment]
CentOS 6 already reached EOL.

There is no need to dare to support it anymore.
